version: '3.5'

services:
  adguardhome:
    image: adguard/adguardhome:latest
    hostname: cip-adguard
    networks:
      - default
    ports:
      - 3000:3000/tcp
    volumes:
      - adguard:/opt/adguardhome/work:z
      - adguard:/opt/adguardhome/conf:z
      
  cyberchef:
    image: mpepping/cyberchef:latest
    hostname: cip-cyberchef
    networks:
      - default

  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki:latest
    hostname: cip-dokuwiki
    networks:
      - default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - dokuwiki:/config:z

  drawio:
    image: fjudith/draw.io:latest
    hostname: cip-draw.io
    networks:
      - default

  ethercalc:
    image: audreyt/ethercalc:latest
    hostname: cip-ethercalc
    networks:
      - default
    environment:
      - REDIS_PORT_6379_TCP_ADDR=cip-ethercalc-redis
      - REDIS_PORT_6379_TCP_PORT=6379
    depends_on:
     - ethercalc-redis
    
  ethercalc_redis:
    image: redis:latest
    hostname: cip-ethercalc-redis
    networks: 
      - default
    volumes:
      - ethercalc_redis:/data:z
    command: redis-server --appendonly yes
    
  etherpad:
    image: tvelocity/etherpad-lite:latest
    hostname: cip-etherpad
    networks:
      - default
    secrets:
      - etherpad_db
    environment:
      - ETHERPAD_TITLE=CIP
      - ETHERPAD_PORT=9001
#      - ETHERPAD_ADMIN_PASSWORD=password
#      - ETHERPAD_ADMIN_USER=admin
      - ETHERPAD_DB_TYPE=mysql
      - ETHERPAD_DB_HOST=cip-etherpad-mysql
      - ETHERPAD_DB_USER=etherpad
      - ETHERPAD_DB_PASSWORD_FILE=/run/secrets/etherpad_db
      - ETHERPAD_DB_NAME=etherpad
    volumes:
      - etherpad:/opt/etherpad-lite/var
    depends_on:
      - etherpad_db
    
  etherpad_db:
    image: mysql:5.7
    hostname: cip-etherpad-mysql
    networks:
      - default
    secrets:
      - etherpad_db
      - etherpad_db_root
    environment:
      - MYSQL_DATABASE=etherpad
      - MYSQL_USER=etherpad
      - MYSQL_PASSWORD_FILE=/run/secrets/etherpad_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/etherpad_db_root
    volumes:
      - etherpad_mysql:/var/lib/mysql:z
    
  gitea:
    image: gitea/gitea:latest
    hostname: cip-gitea
    networks:
      - default
    environment:
      - DB_TYPE=mysql
      - DB_HOST=cip-gitea-mysql:3306
      - DB_NAME=gitea
      - DB_USER=gitea
    ports:
      - 8022:22
    volumes:
      - gitea:/data:z
    depends_on:
      - gitea_db
    
  gitea_db:
    image: mysql:5.7
    hostname: cip-gitea-mysql
    networks:
      - default
    secrets:
      - gitea_db
      - gitea_db_root
    environment:
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD_FILE=/run/secrets/gitea_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/gitea_db_root
    volumes:
      - gitea_mysql:/var/lib/mysql:z

#  heimdall:
#    image: linuxserver/heimdall:latest
#    hostname: cip-heimdall
#    networks:
#      - default
#    environment:
#      - PUID=1001
#      - PGID="1001
#      - TZ=Etc/UTC
#    volumes:
#      - heimdall:/config:z
    
  homer:
    image: b4bz/homer:latest
    hostname: cip-homer
    networks:
      - default
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - homer:/www/assets
    
  pihole:
    image: pihole/pihole:latest
    hostname: cip-pihole
    networks:
      - default
    environment:
      - TZ=Etc/UTC
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - pihole:/etc/pihole:z
      - pihole_dnsmasq:/etc/dnsmasq.d:z
    
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    hostname: cip-rocketchat
    networks:
      - default
    environment:
      - PORT=3000
      - ROOT_URL=http://cip-rocketchat:3000
      - MONGO_URL=mongodb://cip-rocketchat-mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://cip-rocketchat-mongo:27017/local
    volumes:
      - rocketchat:/app/uploads
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - rocketchat_db
    
  rocketchat_db:
    image: mongo:4.0
    hostname: cip-rocketchat-mongo
    networks:
      - default
    volumes:
      - rocketchat_mongo:/data/db:z
      - rocketchat_mongo:/data/configdb:z
      - rocketchat_mongo:/dump:z
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    
  mongo-init-replica:
    image: mongo:4.0
    networks:
      - default
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo cip-rocketchat-mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - rocketchat_db
    
  vaultwarden:
    image: vaultwarden/server:latest
    hostname: cip-vaultwarden
    networks:
      - default
    volumes:
      - vaultwarden:/data/
    
  web:
    image: nginx:latest
    hostname: cip-nginx
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl/cip.crt:/etc/nginx/cip.crt:z
      - ./nginx/ssl/cip.key:/etc/nginx/cip.key:z
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
      - nginx:/var/log/nginx/:z
    depends_on:
      - dokuwiki
      - drawio
      - ethercalc
      - etherpad
      - gitea
#      - heimdall
      - homer
      - owncloud
      - pihole
      - portainer
      - rocketchat
      - vaultwarden
  
secrets:
  etherpad_db:
    external: true
  etherpad_db_root:
    external: true
  gitea_db:
    external: true
  gitea_db_root:
    external: true

volumes:
  adguard:
  dokuwiki:
  ethercalc_redis:
  etherpad:
  etherpad_mysql:
  gitea:
  gitea_mysql:
#  heimdall:
  homer:
  mongo_init:
  nginx:
  pihole:
  pihole_dnsmasq:
  rocketchat:
  rocketchat_mongo:
  vaultwarden:

networks:
  default:
      external: true
      name: cip_default
