version: '3.5'

services:
  dokuwiki:
    hostname: wapes-dokuwiki
    networks:
      - default
    restart: unless-stopped
    image: ghcr.io/linuxserver/dokuwiki:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - dokuwiki:/config:z

  drawio:
    hostname: wapes-draw.io
    networks:
      - default
    restart: unless-stopped
    image: fjudith/draw.io:latest

  ethercalc:
    hostname: wapes-ethercalc
    networks:
      - default
    restart: unless-stopped
    image: audreyt/ethercalc:latest
    environment:
      - REDIS_PORT_6379_TCP_ADDR=wapes-ethercalc-redis
      - REDIS_PORT_6379_TCP_PORT=6379
    depends_on:
     - ethercalc-redis
    
  ethercalc_redis:
    hostname: wapes-ethercalc-redis
    networks: 
      - default
    restart: unless-stopped
    image: redis:latest
    volumes:
      - ethercalc_redis:/data:z
    command: redis-server --appendonly yes
    
  etherpad:
    hostname: wapes-etherpad
    networks:
      - default
    restart: unless-stopped
    image: tvelocity/etherpad-lite:latest
    secrets:
      - etherpad_db
    environment:
      - ETHERPAD_TITLE=WAPES
      - ETHERPAD_PORT=9001
      - ETHERPAD_ADMIN_PASSWORD=password
      - ETHERPAD_ADMIN_USER=admin
      - ETHERPAD_DB_TYPE=mysql
      - ETHERPAD_DB_HOST=wapes-etherpad-mysql
      - ETHERPAD_DB_USER=etherpad
      - ETHERPAD_DB_PASSWORD_FILE=/run/secrets/etherpad_db
      - ETHERPAD_DB_NAME=etherpad
    volumes:
      - etherpad:/opt/etherpad-lite/var
    depends_on:
      - etherpad_db
    
  etherpad_db:
    hostname: wapes-etherpad-mysql
    networks:
      - default
    restart: unless-stopped
    image: mysql:5.7
    secrets:
      - etherpad_db
      - etherpad_db_root
    environment:
      - MYSQL_DATABASE=etherpad
      - MYSQL_USER=etherpad
      - MYSQL_PASSWORD_FILE=/run/secrets/etherpad_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/etherpad_db_root
    volumes:
      - etherpad_mysql:/var/lib/mysql:z
    
  gitea:
    hostname: wapes-gitea
    networks:
      - default
    restart: unless-stopped
    image: gitea/gitea:latest
    secrets:
      - gitea_db
    environment:
      - DB_TYPE=mysql
      - DB_HOST=wapes-gitea-mysql:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD_FILE=/run/secrets/gitea_db
    ports:
      - 8022:22
    volumes:
      - gitea:/data:z
    depends_on:
      - gitea_db
    
  gitea_db:
    hostname: wapes-gitea-mysql
    networks:
      - default
    restart: unless-stopped
    image: mysql:5.7
    secrets:
      - gitea_db
      - gitea_db_root
    environment:
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD_FILE=/run/secrets/gitea_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/gitea_db_root
    volumes:
      - gitea_mysql:/var/lib/mysql:z

  heimdall:
    hostname: wapes-heimdall
    networks:
      - default
    restart: unless-stopped
    image: linuxserver/heimdall:latest
    environment:
      - PUID=1001
      - PGID="1001
      - TZ=Etc/UTC
    volumes:
      - heimdall:/config:z
    
  homer:
    hostname: wapes-homer
    networks:
      - default
    restart: unless-stopped
    image: b4bz/homer:latest
    volumes:
      - homer:/www/assets
    
  owncloud:
    hostname: wapes-owncloud
    networks:
      - default
    restart: unless-stopped
    image: owncloud:9
    volumes:
      - owncloud:/var/www/html
    depends_on:
      - owncloud-mariadb
    
  owncloud-mariadb:
    hostname: wapes-owncloud-mariadb
    networks:
      - default
    restart: unless-stopped
    image: mariadb:latest
    secrets:
      - owncloud_db
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/owncloud_db
    volumes:
      - owncloud_mariadb:/var/lib/mysql
    
  pihole:
    hostname: wapes-pihole
    networks:
      - default
    restart: unless-stopped
    image: pihole/pihole:latest
    environment:
      - TZ=Etc/UTC
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - pihole:/etc/pihole:z
      - pihole_dnsmasq:/etc/dnsmasq.d:z
    
  portainer:
    hostname: wapes-portainer
    networks:
      - default
    restart: unless-stopped
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    volumes:
      - portainer:/data:z
      - ./portainer/ssl:/certs:z
      - /var/run/docker.sock:/var/run/docker.sock
    command: --ssl --sslcert /certs/portainer.crt --sslkey /certs/portainer.key --no-analytics
    
  rocketchat:
    hostname: wapes-rocketchat
    networks:
      - default
    restart: unless-stopped
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    environment:
      - PORT=3000
      - ROOT_URL=http://wapes-rocketchat:3000
      - MONGO_URL=mongodb://wapes-rocketchat-mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://wapes-rocketchat-mongo:27017/local
    volumes:
      - rocketchat:/app/uploads
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - rocketchat_db
    
  rocketchat_db:
    hostname: wapes-rocketchat-mongo
    networks:
      - default
    restart: unless-stopped
    image: mongo:4.0
    volumes:
      - rocketchat_mongo:/data/db:z
      - rocketchat_mongo:/data/configdb:z
      - rocketchat_mongo:/dump:z
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    
  mongo-init-replica:
    networks:
      - default
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo wapes-rocketchat-mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - rocketchat_db
    
  vaultwarden:
    hostname: wapes-vaultwarden
    networks:
      - default
    restart: unless-stopped
    image: vaultwarden/server:latest
    volumes:
      - vaultwarden:/data/
    
  web:
    hostname: wapes-nginx
    networks:
      - default
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl/wapes.crt:/etc/nginx/wapes.crt:z
      - ./nginx/ssl/wapes.key:/etc/nginx/wapes.key:z
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
      - nginx:/var/log/nginx/:z
    depends_on:
      - dokuwiki
      - drawio
      - ethercalc
      - etherpad
      - gitea
      - heimdall
      - homer
      - owncloud
      - pihole
      - portainer
      - rocketchat
      - vaultwarden
  
secrets:
  etherpad_db:
    external: true
  etherpad_db_root:
    external: true
  gitea_db:
    external: true
  gitea_db_root:
    external: true
  owncloud_db:
    external: true
  owncloud_db_root:
    external: true

volumes:
  dokuwiki:
  ethercalc_redis:
  etherpad:
  etherpad_mysql:
  gitea:
  gitea_mysql:
  heimdall:
  homer:
  nginx:
  owncloud:
  owncloud_mariadb:
  pihole:
  pihole_dnsmasq:
  portainer:
  rocketchat:
  rocketchat_mongo:
  vaultwarden:

networks:
  default: