# traefik.toml
# To redirect an http entrypoint to an https entrypoint (with SNI support):

defaultEntryPoints = ["http", "https"]

 [entryPoints]
   [entryPoints.http]
   address = ":80"
     [entryPoints.http.redirect]
       entryPoint = "https"
   [entryPoints.https]
   address = ":443"
     [entryPoints.https.tls]
       [[entryPoints.https.tls.certificates]]
       CertFile = "integration/fixtures/https/snitest.com.cert"
       KeyFile = "integration/fixtures/https/snitest.com.key"
   [entryPoints.dashboard]
   address=":8080"
#     [entryPoints.dashboard.auth]
#      [entryPoints.dashboard.auth.basic]
#        usersFile = "/etc/traefik/.htpasswd"
		
[providers]
  [providers.docker]
    exposedByDefault = false
	endpoint = "unix:///var/run/docker.sock"
	
[api]
entrypoint = "dashboard"